<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>sblngavnav6.TelegramExtensions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\external\DTF\DTF.csproj" />
  </ItemGroup>
</Project>
